# Generated by Django 4.1.2 on 2022-11-24 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Userinfo',
        ),
    ]
