# Generated by Django 4.1.2 on 2022-11-28 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_userinfo_cover_alter_userinfo_profil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='cover',
            field=models.ImageField(upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='profil',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
