# Generated by Django 4.1.2 on 2022-12-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_userpost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='userpost',
        ),
    ]
