# Generated by Django 4.1.2 on 2022-12-06 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_delete_userpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='userpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('postphoto', models.ImageField(upload_to='Images')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.userinfo')),
            ],
            options={
                'db_table': 'userpost',
            },
        ),
    ]
