# Generated by Django 4.1.2 on 2022-12-07 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_userpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='posttime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
